config/routes.rb
Kidsland::Application.routes.draw do
  resources :answers

  resources :variants

  resources :questions

  resources :jobs

  resources :services

  resources :people

  get "pages/home"

  post "headshot/capture" => 'headshot#capture', :as => :headshot_capture
  get "admin" => 'answers#index'
  devise_for :users
  resources :resume
  root :to => 'resume#show'

end

app/models/person.rb
class Person < ActiveRecord::Base
  attr_accessible :first_name, :last_name, :sex, :dob, :age, :school_number, :school_type, :klass, :headshot_photo_id
  #belongs_to :headshot_photo
  has_many :headshot_photos, :as => :capturable
  has_and_belongs_to_many :variants
  after_create :clear

  def clear
    Person.where(["created_at < ?", 2.days.ago]).delete_all 
  end
 

  def show_answer(lang)
    list = []
    self.variants.each do |variant|
      list += variant.answer_ids
    end
    answer_id = list.group_by{|a| a }.sort_by{|a,b| b.size<=>a.size}.first[0]
    answer = Answer.find(answer_id)

    return  lang == "ukr" ? answer.content : answer.content_rus   
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  def index
    @people = Person.all
  end

  def show
    @person = Person.find(params[:id])
  end

  def new
    @person = Person.new
  end

  def create
    @person = Person.new(params[:person])
    if @person.save
      redirect_to @person, :notice => "Successfully created person."
    else
      render :action => 'new'
    end
  end

  def edit
    @person = Person.find(params[:id])
  end

  def update
    @person = Person.find(params[:id])
    if @person.update_attributes(params[:person])
      redirect_to @person, :notice  => "Successfully updated person."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @person = Person.find(params[:id])
    @person.destroy
    redirect_to people_url, :notice => "Successfully destroyed person."
  end
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/people/_form.html.erb
<%= form_for @person, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :first_name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :first_name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :last_name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :last_name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :sex, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :sex, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :dob, :class => 'control-label' %>
    <div class="controls">
      <%= f.date_select :dob, :class => 'date_select' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :school_number, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :school_number, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :school_type, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :school_type, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :klass, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :klass, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group"  style="display:none;">
    <%= f.label :headshot_photo, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :headshot_photo, :class => 'number_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit "Сохранить", :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                people_path, :class => 'btn' %>
  </div>
<% end %>

app/views/people/edit.html.erb
<%- model_class = Person -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/people/index.html.erb
<%- model_class = Person -%>
<div class="page-header">
 <h5> Список резюме </h5>
</div>
<table class="table table-striped">
  <thead>
  </thead>
  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td><%= link_to person.id, person_path(person) %></td>
        <td><%= person.first_name %></td>
        <td><%= person.last_name %></td>
        <td><%=l person.created_at %></td>
        <td>
          <%= link_to "Открыть",
                      person_path(person), :class => 'btn btn-mini' %>
          <%= link_to "Удалить",
                      person_path(person),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_person_path,
            :class => 'btn btn-primary' %>

app/views/people/new.html.erb
<%- model_class = Person -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/people/show.html.erb
 <script>  
  $(document).ready(function() {
    $(".btnPrint").printPage(
    {
      url: "/resume/print_resume",
      attr: "href",
      message:"Идет печать ..."
}
    );
  });
</script>

<div class="row">
  <div class="span4 offset4">
  <h2 class="muted"> Резюме </h2>
</div>
</div>
<%# @person = Person.last %>
<%- model_class = Person -%>
<hr>

<div class="alert alert-info">
  <h4><%=t '.title', :default => "Персональная ифнормация:" %></h4>
</div>
<div class="row" >
 
  <div class="span8">
    <h4>
    <dl class="dl-horizontal">
    <dt><strong>Имя:</strong></dt>
    <dd><%= @person.first_name %></dd>
    <dt><strong>Фамилия: </strong></dt>
    <dd><%= @person.last_name %></dd>
    <dt><strong>Пол:</strong></dt>
    <dd><%= @person.sex %></dd>
    <dt><strong>№:</strong></dt>
    <dd><%= @person.school_number %></dd>
    <dt><strong>Тип:</strong></dt>
    <dd><%= @person.school_type %></dd>
    <dt><strong>Класс:</strong></dt>
    <dd><%= @person.klass %></dd>
  </dl>
  </h4>
  </div>
  <div class="span4" >
 <a href="#" class="thumbnail">
                  <img data-src="holder.js/260x180" alt="">
                </a>
  </div>

</div>
<hr>
<div class="alert alert-info">
  <h4><%=t '.title', :default => "Интересы:" %></h4>
</div>
<div class="row ">
  <div class="span6 offset3 muted">
    <ul>
      <% @person.variants.each do |variant| %> 
        <li> <h5> <%= variant.text %> </h5> </li>
      <% end %>
    </ul>
  </div>
</div>

<hr>
<div class="alert alert-info">
  <h4><%=t '.title', :default => "Рекомендуемая сфера деятельности:" %></h4>
</div>
<div class="row ">
  <div class="span6 offset3 muted">
    <h5> <%= Service.first.name %> </h5>
  </div>
</div>

<hr>
<div  class="alert alert-info">
  <h4><%=t '.title', :default => "Рекомендуемые профессии КидЛандии:" %></h4>
</div>
<div class="row ">
  <div class="span6 offset3 muted ">
    <%
    list=""  
    @person.variants.each do |variant|
      variant.jobs.each do |job|
        list << " #{job.name} "
      end
    end
    %>
    <% list.split(" ").each do |l|%>
      <li> <h5> <%= l %></h5> </li>
    <% end %>
      <h4> <%#= list %></h4>
  </div>
</div>
<hr />

<div class="form-actions">
  <a class="btnPrint btn btn-primary btn-large" href='iframes/iframe.html' id="print_link">Распечатать</a>
  <%= link_to "Назад",
    people_path, :class => 'btn'  %>
</div>