config/routes.rb
Kidsland::Application.routes.draw do
  resources :answers

  resources :variants

  resources :questions

  resources :jobs

  resources :services

  resources :people

  get "pages/home"

  post "headshot/capture" => 'headshot#capture', :as => :headshot_capture
  get "admin" => 'answers#index'
  devise_for :users
  resources :resume
  root :to => 'resume#show'

end

app/controllers/resume_controller.rb
class ResumeController < ApplicationController
  helper :headshot
  # before_filter :authenticate_user!
  include Wicked::Wizard
  
  steps :start_page ,:info, :question1, :question2, :question3, :question4, 
       :question5, :question6, :question7, :question8, :question9, :question10, :question11,
       :question12, :results


 def show
  #  @user = current_user
  case step
  when :start_page
    @person = Person.create
    cookies[:person_id] = @person.id
  when :info
    @person = Person.find(cookies[:person_id])
  end  
   render_wizard
 end

 def update
  @person = Person.find(cookies[:person_id])
  case step
  when :start_page
      cookies[:lang] = params[:lang]
  when :info
      @person.attributes = params[:person]
    when :question1
      @person.variants << Variant.find_by_id(params[:variant].to_i)
    when :question2
      @person.variants << Variant.find_by_id(params[:variant].to_i)
    when :question3
      @person.variants << Variant.find_by_id(params[:variant].to_i)
    when :question4
      @person.variants << Variant.find_by_id(params[:variant].to_i)
    when :question5
      @person.variants << Variant.find_by_id(params[:variant].to_i)
    when :question6
      @person.variants << Variant.find_by_id(params[:variant].to_i)
    when :question7
      @person.variants << Variant.find_by_id(params[:variant].to_i)
    when :question8
      @person.variants << Variant.find_by_id(params[:variant].to_i)
    when :question9
      @person.variants << Variant.find_by_id(params[:variant].to_i)
    when :question10
      @person.variants << Variant.find_by_id(params[:variant].to_i)
    when :question11
      @person.variants << Variant.find_by_id(params[:variant].to_i)
    when :question12
      @person.variants << Variant.find_by_id(params[:variant].to_i)
    end
     
   render_wizard @person
  end

#def create

#  case step
# when :info
#   @person = Person.create
# end 
# 
#   redirect_to wizard_path(steps.first, :product_id => @product.id)
# end


end

app/helpers/resume_helper.rb
module ResumeHelper
end

app/views/resume/answer_question.html.erb
<h1>  Сдесь будут вопросы ... </h1>
<br  />
  <hr>
  <p>
    <%= link_to 'Далее', next_wizard_path, :class=> "btn btn-primary btn-large pull-right"%>
  </p>

app/views/resume/info.html.erb
<div class=row>
  <div class="span6 offset2" >
    <%= image_tag("other.jpg") %>
  </div>
</div>

  <hr>
  <div class="alert alert-info">
    <% if cookies[:lang] == "ukr" %>
      <h4> Вкажіть ваше ім'я: </h4>
    <% else %>
      <h4> Укажите имя: </h4>
    <% end %>  
  </div>
<hr>

<div class="row">
  <div class="span6 offset3">
<%= form_for @person,  url: wizard_path,  :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <% if cookies[:lang] == "ukr" %>
      <%= f.label "Ім'я:", :class => 'control-label' %> 
    <% else %>
      <%= f.label "Имя:", :class => 'control-label' %> 
    <% end %>  
    <div class="controls">
      <% if cookies[:lang] == "ukr" %>
        <%= f.text_field :first_name, :class => 'text_field' , :required => true, :title=>"Заповніть це поле" %>
      <% else %>
        <%= f.text_field :first_name, :class => 'text_field' , :required => true, :title=>"Заполните это поле" %>
      <% end %>
    </div>
  </div>

<hr>
</div>
</div>
  <div class="form-actions  pagination-centered">
    <% if cookies[:lang] == "ukr" %>
      <%= f.submit "Далі", :class => 'btn btn-primary btn-large ' %>
    <% else %>
      <%= f.submit "Дальше", :class => 'btn btn-primary btn-large ' %>
    <% end %>
  </div>
<% end %>

app/views/resume/make_photo.html.erb
<script language="JavaScript"> 
var customCameraHooks = {
  onComplete: function(response) {
  $('#next').css('visibility','visible');
}
};
</script>
<div class="alert alert-info">
<h2>Дивись у камеру, посміхнись і нажми кнопку "Фото" коли будеш готовий ☺</h2>
</div>
<hr>
<div class="pagination-centered" >

<%= headshot_default_config(Rails.application.config.session_options[:key], headshot_capture_path, :on_complete => "customCameraHooks.onComplete") %>

<%= headshot_camera %>

<br/>
<hr>
<button name="button" onclick="headshotHandlers.snap()" type="submit" class="btn btn-success btn-large">Фото</button>
<button name="button" onclick="headshot.configure()" type="submit">Настройка</button>

</div>
<br  />
<hr>
  <div class="form-actions pagination-centered" >
    <%= link_to 'Далі', next_wizard_path,:id=>"next", :class=> " btn btn-primary btn-large" , :style=>"visibility:hidden;"%>
  </div>

app/views/resume/print_resume.html.erb
 <script>  
  $(document).ready(function() {
    $(".btnPrint").printPage(
    {
      url: "/resume/print_resume",
      attr: "href",
      message:"Идет печать ..."
}
    );
  });
</script>
<div id="print_page">
<div class="row">
  <div class="span4 offset4">
    <h2 class="muted"> Резюме </h2>
  </div>
</div>
<% @person = Person.last %>
<%- model_class = Person -%>
<div class="alert alert-info">
  <h4><%=t '.title', :default => "Персональна інформація:" %></h4>
</div>
<table class="table" >
  <tr  >
    <td style="width:50%">
      <table style="width:90%;">
        <tr>
          <td> Ім'я:</td>
          <td> <%= @person.first_name %></td>
        </tr>
        <tr>
          <td> Прізвище:</td>
          <td> <%= @person.last_name %></td>
        </tr>
        <tr>
          <td> Стать:</td>
          <td> <%= @person.sex %></td>
        </tr>
        <tr>
          <td> Вік:</td>
          <td> <%= @person.age %></td>
        </tr>
        <tr>
          <td>Місце навчання: </td>
          <td> <%= @person.school_type %> №:<%= @person.school_number %>, <%= @person.klass %>  </td>
        </tr>
      </table>  
    
    </td>
    <td style="width:50%;">
      <div class="pagination-centered" >
        <% if @person.headshot_photos.size >0  %>
          <%= image_tag "/headshots/#{@person.headshot_photos.last.image_file_name}" , :size => "200x200" %>
        <% end %>
      </div>
    </td>
  
  </tr>
</table>
<%
=begin
%>
<div class="row" >
 
  <div class="span4">
    <h4>
    <dl class="dl-horizontal">
    <dt><strong>Имя:</strong></dt>
    <dd><%= @person.first_name %></dd>
    <dt><strong>Фамилия: </strong></dt>
    <dd><%= @person.last_name %></dd>
    <dt><strong>Пол:</strong></dt>
    <dd><%= @person.sex %></dd>
    <dt><strong>Возраст:</strong></dt>
    <dd><%= @person.age %></dd>
  </dl>
  </h4>
</div>
  <div class="span4">
    <h4>
    <dl class="dl-horizontal">
      <dt><strong><%= @person.school_type %> №:</strong></dt>
    <dd><%= @person.school_number %></dd>
    <dt><strong>Класс:</strong></dt>
    <dd><%= @person.klass %></dd>
  </dl>
  </h4>
</div>


  <div class="span4" >
    <a href="#" class="thumbnail">
          <img data-src="holder.js/260x180" alt="">
      </a>
  </div>

</div>
<%
=end
%>
<hr>
<div class="alert alert-info interests" >
  <h4><%=t '.title', :default => "Інтереси:" %></h4>
</div>
<div class="row  interests">
  <div class="span6 offset3 muted">
    <ul>
      <% @person.variants.each do |variant| %> 
        <li> <h5> <%= variant.text %> </h5> </li>
      <% end %>
    </ul>
  </div>
</div>

<hr>
<div class="alert alert-info">
  <h4><%=t '.title', :default => "Рекомендовані сфери діяльності:" %></h4>
</div>
<div class="row ">
  <div class="span6 offset3 muted">
    <% list_services = []
    @person.variants.each do |variant|
      variant.jobs.each do |job|
        list_services << job.service.name if list_services.include?("#{job.service.name}") == false
      end
    end
    %>
    <% list_services.each do |service| %>
      <%= "#{service}, "  %>
    <% end%>
  </div>
</div>

<hr>
<div  class="alert alert-info">
  <h4><%=t '.title', :default => "Рекомендовані професії" %></h4>
</div>
<div class="row ">
  <div class="span6 offset3 muted ">
    <%
      list=""
    list_services=[]  
    @person.variants.each do |variant|
      variant.jobs.each do |job|
        list << " #{job.name} "
      end
    end
    %>
    <table>
      <tr>
        <% list.split(" ").each_slice(5) do |slice|%>
          <td>
            <ul>
            <% slice.each do |l| %>
              <li> <h5> <%= l %></h5> </li>
            <% end %>
            </ul>
          </td>
        <% end %>
      </tr>
    </table>
  </div>
</div>
<hr />
  <p class="pagination-centered"> <a class="btnPrint btn btn-primary btn-large" href='iframes/iframe.html' id="print_link">Роздрукувати</a></p>
</div>

app/views/resume/question10.html.erb
<div class=row>
  <div class="span6 offset2" >
    <%= image_tag("other.jpg") %>
  </div>
</div>
<hr>

<% @question = Question.all[9] %>

<div class="alert alert-info">
  <h3> <%=cookies[:lang] == "ukr" ?  @question.text : @question.text_rus %> </h3>
</div>
<%= form_tag("/resume/question10" , :method => :put)  do  %>
 <%= render "/resume/variants_list" %>
  <hr>
  <div class="form-actions pagination-centered">
     <% if cookies[:lang] == "ukr"%>
      <%= submit_tag "Далі" , :class=> " btn btn-primary btn-large"%>
    <% else %>
      <%= submit_tag "Дальше" , :class=> " btn btn-primary btn-large"%>
    <% end %> 
  </div>
<% end %>


<br  />

app/views/resume/question12.html.erb
<div class=row>
  <div class="span6 offset2" >
    <%= image_tag("other.jpg") %>
  </div>
</div>
<hr>

<% @question = Question.all[11] %>

<div class="alert alert-info">
  <h3> <%=cookies[:lang] == "ukr" ?  @question.text : @question.text_rus %> </h3>
</div>
<%= form_tag("/resume/question12" , :method => :put)  do  %>
  <%= render "/resume/variants_list" %>
  <hr>
  <div class="form-actions pagination-centered">
   <% if cookies[:lang] == "ukr"%>
      <%= submit_tag "Далі" , :class=> " btn btn-primary btn-large"%>
    <% else %>
      <%= submit_tag "Дальше" , :class=> " btn btn-primary btn-large"%>
    <% end %> 
  </div>
<% end %>
<br  />

app/views/resume/question3.html.erb
<div class=row>
  <div class="span6 offset2" >
    <%= image_tag("other.jpg") %>
  </div>
</div>
<hr>
<% @question = Question.all[2] %>

<div class="alert alert-info">
  <h3> <%=cookies[:lang] == "ukr" ?  @question.text : @question.text_rus %> </h3>
</div>
<%= form_tag("/resume/question3" , :method => :put)  do  %>
  <%= render "/resume/variants_list" %>
  <hr>
  <div class="form-actions pagination-centered">
     <% if cookies[:lang] == "ukr"%>
      <%= submit_tag "Далі" , :class=> " btn btn-primary btn-large"%>
    <% else %>
      <%= submit_tag "Дальше" , :class=> " btn btn-primary btn-large"%>
    <% end %> 
  </div>
<% end %>

app/views/resume/question5.html.erb
<div class=row>
  <div class="span6 offset2" >
    <%= image_tag("other.jpg") %>
  </div>
</div>
<hr>

<% @question = Question.all[4] %>

<div class="alert alert-info">
  <h3> <%=cookies[:lang] == "ukr" ?  @question.text : @question.text_rus %> </h3>
</div>
<%= form_tag("/resume/question5" , :method => :put)  do  %>
 <%= render "/resume/variants_list" %>
  <hr>
  <div class="form-actions pagination-centered">
     <% if cookies[:lang] == "ukr"%>
      <%= submit_tag "Далі" , :class=> " btn btn-primary btn-large"%>
    <% else %>
      <%= submit_tag "Дальше" , :class=> " btn btn-primary btn-large"%>
    <% end %> 
  </div>
<% end %>


<br  />

app/views/resume/question6.html.erb
<div class=row>
  <div class="span6 offset2" >
    <%= image_tag("other.jpg") %>
  </div>
</div>
<hr>

<% @question = Question.all[5] %>

<div class="alert alert-info">
  <h3> <%=cookies[:lang] == "ukr" ?  @question.text : @question.text_rus %> </h3>
</div>
<%= form_tag("/resume/question6" , :method => :put)  do  %>
 <%= render "/resume/variants_list" %>
  <hr>
  <div class="form-actions pagination-centered">
     <% if cookies[:lang] == "ukr"%>
      <%= submit_tag "Далі" , :class=> " btn btn-primary btn-large"%>
    <% else %>
      <%= submit_tag "Дальше" , :class=> " btn btn-primary btn-large"%>
    <% end %> 
  </div>
<% end %>


<br  />

app/views/resume/question7.html.erb
<div class=row>
  <div class="span6 offset2" >
    <%= image_tag("other.jpg") %>
  </div>
</div>
<hr>

<% @question = Question.all[6] %>

<div class="alert alert-info">
  <h3> <%=cookies[:lang] == "ukr" ?  @question.text : @question.text_rus %> </h3>
</div>
<%= form_tag("/resume/question7" , :method => :put)  do  %>
  <%= render "/resume/variants_list" %>
  <hr>
  <div class="form-actions pagination-centered">
     <% if cookies[:lang] == "ukr"%>
      <%= submit_tag "Далі" , :class=> " btn btn-primary btn-large"%>
    <% else %>
      <%= submit_tag "Дальше" , :class=> " btn btn-primary btn-large"%>
    <% end %> 
  </div>
<% end %>


<br  />

app/views/resume/question8.html.erb
<div class=row>
  <div class="span6 offset2" >
    <%= image_tag("other.jpg") %>
  </div>
</div>
<hr>
<% @question = Question.all[7] %>

<div class="alert alert-info">
  <h3> <%=cookies[:lang] == "ukr" ?  @question.text : @question.text_rus %> </h3>
</div>
<%= form_tag("/resume/question8" , :method => :put)  do  %>
  <%= render "/resume/variants_list" %>
  <hr>
  <div class="form-actions pagination-centered">
     <% if cookies[:lang] == "ukr"%>
      <%= submit_tag "Далі" , :class=> " btn btn-primary btn-large"%>
    <% else %>
      <%= submit_tag "Дальше" , :class=> " btn btn-primary btn-large"%>
    <% end %> 
  </div>
<% end %>


<br  />

app/views/resume/question9.html.erb
<div class=row>
  <div class="span6 offset2" >
    <%= image_tag("other.jpg") %>
  </div>
</div>
<hr>

<% @question = Question.all[8] %>

<div class="alert alert-info">
  <h3> <%=cookies[:lang] == "ukr" ?  @question.text : @question.text_rus %> </h3>
</div>
<%= form_tag("/resume/question9" , :method => :put)  do  %>
  <%= render "/resume/variants_list" %>
  <hr>
  <div class="form-actions pagination-centered">
     <% if cookies[:lang] == "ukr"%>
      <%= submit_tag "Далі" , :class=> " btn btn-primary btn-large"%>
    <% else %>
      <%= submit_tag "Дальше" , :class=> " btn btn-primary btn-large"%>
    <% end %> 
  </div>
<% end %>


<br  />

app/views/resume/results.html.erb
 <script>  
  $(document).ready(function() {
    $(".btnPrint").printPage(
    {
      url: "/resume/results",
      attr: "href",
      message:"Идет печать ..."
}
    );
  });
</script>

<div id="print_page">
<% @person = Person.find(cookies[:person_id]) %>
<%- model_class = Person -%>
  <div class="alert alert-info">
    <% if cookies[:lang] == "ukr" %>
      <h4><%=t '.title', :default => "Результати теста:" %></h4>
    <% else %> 
      <h4><%=t '.title', :default => "Результаты теста:" %></h4>
    <% end %> 
  </div>
  <span id="res" style="color:gray">
    <%= @person.show_answer(cookies[:lang]) %>
  </span>
</div>
<hr />
 <% if cookies[:lang] == "ukr" %>
  <p class="pagination-centered"> <a class="btnPrint btn btn-primary btn-large" href='iframes/iframe.html' id="print_link">Роздрукувати</a></p>
 <% else %>
  <p class="pagination-centered"> <a class="btnPrint btn btn-primary btn-large" href='iframes/iframe.html' id="print_link">Печать</a></p>
 <% end %>

app/views/resume/start_page.html.erb
<div class="alert alert-info">
  <div class="row">
    <div class="span3">
      <%= image_tag "kidslandia_logo.jpg", :style=>"width:150px;" %>
    </div> 
    <div class="span8">
      <h2 >  ТВІЙ НАЙКРАЩИЙ ВІДПОЧИНОК  </h2>
      <h2 >  ТВОЙ ЛУЧШИЙ ОТДЫХ  </h2>
    </div>
  </div>
</div>
<hr>
<div class="row">
 
    <div class="span8 offset2">
      <%= image_tag("start.jpg") %>
    </div>
 
    <div class="span4">
    </div>
    
  </div>
  <br  />
  <hr>
<div class="row">
  <div class="span4 offset2">
    <%= form_tag("/resume/start_page" , :method => :put)  do  %>
      <%= hidden_field_tag(:lang, "rus") %>
      <div class="form-actions pagination-centered">
        <%= submit_tag "Русский" , :class=> " btn btn-primary btn-large"%>
      </div>
    <% end %>
  </div>
  <div class="span4">
    <%= form_tag("/resume/start_page" , :method => :put)  do  %>
      <%= hidden_field_tag(:lang, "ukr") %>
      <div class="form-actions pagination-centered">
        <%= submit_tag "Українська" , :class=> " btn btn-primary btn-large"%>
      </div>
    <% end %>
  </div>  
</div>

<%
=begin
%>
<div class="form-actions  pagination-centered">
    <%= link_to 'Далі', next_wizard_path, :class=> "btn btn-primary btn-large "%>
  </div>

<%
=end
%>