config/routes.rb
Kidsland::Application.routes.draw do
  resources :answers

  resources :variants

  resources :questions

  resources :jobs

  resources :services

  resources :people

  get "pages/home"

  post "headshot/capture" => 'headshot#capture', :as => :headshot_capture
  get "admin" => 'answers#index'
  devise_for :users
  resources :resume
  root :to => 'resume#show'

end

app/models/answer.rb
class Answer < ActiveRecord::Base
 # attr_accessible :content
  has_and_belongs_to_many :variants
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
 before_filter :authenticate_user!
  def index
    @answers = Answer.all
    @questions = Question.all
  end

  def show
    @answer = Answer.find(params[:id])
  end

  def new
    @answer = Answer.new
  end

  def create
    @answer = Answer.new(params[:answer])
    if @answer.save
      redirect_to answers_url, :notice => "Successfully created answer."
    else
      render :action => 'new'
    end
  end

  def edit
    @answer = Answer.find(params[:id])
  end

  def update
    @answer = Answer.find(params[:id])
    if @answer.update_attributes(params[:answer])
      redirect_to answers_url, :notice  => "Successfully updated answer."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @answer = Answer.find(params[:id])
    @answer.destroy
    redirect_to answers_url, :notice => "Successfully destroyed answer."
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_form.html.erb
<%= form_for @answer, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    Укр.
    <div class="controls">
      <%= f.text_area :content, :class => 'text_area', :rows=>8, :style=>"width:700px;" %>
    </div>
    Рус.
    <div class="controls">
      <%= f.text_area :content_rus, :class => 'text_area', :rows=>8, :style=>"width:700px;" %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit "Сохранить", :class => 'btn btn-primary' %>
    <%= link_to "Отмена",
                answers_path, :class => 'btn' %>
  </div>
<% end %>

app/views/answers/edit.html.erb
<%- model_class = Answer -%>
<div class="page-header">
  <h4>Редактирование:</h4>
</div>
<%= render :partial => 'form' %>

app/views/answers/index.html.erb
<%- model_class = Answer -%>
<div class="alert alert-info">
  <h4><%=t '.title', :default =>"Ответы:"  %></h4>
</div>
<table class="table table-striped">
    <tbody>
    <% @answers.each do |answer| %>
      <tr>
        <td style="width:75%;"><%= answer.content %></td>
        <td>
          <%= link_to 'Редактировать',
                      edit_answer_path(answer), :class => 'btn btn-mini' %>
          <%= link_to 'Удалить',
                      answer_path(answer),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Добавить',
            new_answer_path,
            :class => 'btn btn-primary' %>
<br />
            <br />

<%- model_class = Question -%>
<div class="page-header">
</div>
<div class="alert alert-info">
  <h4><%=t '.title', :default =>"Вопросы:"  %></h4>
</div>
<table class="table table-striped">
  
  <tbody>
    <% @questions.each do |question| %>
      <tr>
        <td style="width:85%;">
          <%= question.text %>
          <br />
          <ul class="">
            <% question.variants.each do |variant|%>
              <% if question.images == true %>
                <li> <%= variant.text %>   <span class="muted"> ( <%= link_to "ред. привязку", :controller => :variants, :action => :edit , :id => variant.id %> ) 
                    <br>
 <%= image_tag variant.image.url(:thumb) %>
                  </li>
              <% else %>     
                <li> <%= variant.text %>   <span class="muted"> (<%= link_to "ред. привязку", :controller => :variants, :action => :edit , :id => variant.id %> ) </li>
              <% end %> 
          <% end %>
          </ul>
        </td>
        <td>
          <%= link_to "Редактировать",
                      edit_question_path(question), :class => 'btn btn-mini' %>
          <%= link_to  "Удалить",
                      question_path(question),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
     
    <% end %>
  </tbody>
</table>
<% if Question.all.size < 12 %>
  <%= link_to "Добавить",  new_question_path, :class => 'btn btn-primary' %>
<% end %>

app/views/answers/new.html.erb
<%- model_class = Answer -%>
<div class="page-header">
  <h4> Новый ответ: </h4>
</div>
<%= render :partial => 'form' %>

app/views/answers/show.html.erb
<%- model_class = Answer -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:content) %>:</strong></dt>
  <dd><%= @answer.content %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              answers_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_answer_path(@answer), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              answer_path(@answer),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>