config/routes.rb
Kidsland::Application.routes.draw do
  resources :answers

  resources :variants

  resources :questions

  resources :jobs

  resources :services

  resources :people

  get "pages/home"

  post "headshot/capture" => 'headshot#capture', :as => :headshot_capture
  get "admin" => 'answers#index'
  devise_for :users
  resources :resume
  root :to => 'resume#show'

end

app/models/variant.rb
class Variant < ActiveRecord::Base
  #attr_accessible :text, :question_id
  has_attached_file :image, :styles => { :medium => "200x200#", :thumb => "100x100#" }
validates_attachment_content_type :image, :content_type => %w(image/jpeg image/jpg image/png)
  belongs_to :question
  has_and_belongs_to_many :people
  has_and_belongs_to_many :answers
  has_and_belongs_to_many :jobs
  accepts_nested_attributes_for :jobs
end

app/controllers/variants_controller.rb
class VariantsController < ApplicationController
 before_filter :authenticate_user!
  def index
    @variants = Variant.all
  end

  def show
    @variant = Variant.find(params[:id])
  end

  def new
    @variant = Variant.new
  end

  def create
    @variant = Variant.new(params[:variant])
    if @variant.save
      redirect_to answers_url, :notice => "Successfully created variant."
    else
      render :action => 'new'
    end
  end

  def edit
    @variant = Variant.find(params[:id])
  end

  def update
    @variant = Variant.find(params[:id])
    if @variant.update_attributes(params[:variant])
      redirect_to answers_url, :notice  => "Successfully updated variant."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @variant = Variant.find(params[:id])
    @variant.destroy
    redirect_to answers_url, :notice => "Successfully destroyed variant."
  end
end

app/helpers/variants_helper.rb
module VariantsHelper
end

app/views/variants/_form.html.erb
<%= form_for @variant, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label "Значение", :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :text, :class => 'text_area', :rows=>2 %>
    </div>
  </div>
  <div class="control-group" style="display:none;">
    <%= f.label :question_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :question_id, :class => 'number_field' %>
    </div>
  </div>

  <% for answer in Answer.find(:all) %>
<div>
  <%= check_box_tag "variant[answer_ids][]", answer.id, @variant.answers.include?(answer) %>
  <%= answer.content %>
  <hr>
</div>
<% end %>
  <div class="form-actions">
    <%= f.submit "Сохранить", :class => 'btn btn-primary' %>
    <%= link_to "Отмена",
                answers_path, :class => 'btn' %>
  </div>
<% end %>

app/views/variants/edit.html.erb
<%- model_class = Variant -%>
<div class="page-header">
  <h5> Вариант </h5>
  <p class="muted"> Сдесь вариант  привязываеться к одному либо нескольким ответам.</p>
</div>
<%= render :partial => 'form' %>

app/views/variants/index.html.erb
<%- model_class = Variant -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:text) %></th>
      <th><%= model_class.human_attribute_name(:question_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @variants.each do |variant| %>
      <tr>
        <td><%= link_to variant.id, variant_path(variant) %></td>
        <td><%= variant.text %></td>
        <td><%= variant.question_id %></td>
        <td><%=l variant.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_variant_path(variant), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      variant_path(variant),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_variant_path,
            :class => 'btn btn-primary' %>

app/views/variants/new.html.erb
<%- model_class = Variant -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/variants/show.html.erb
<%- model_class = Variant -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:text) %>:</strong></dt>
  <dd><%= @variant.text %></dd>
  <dt><strong><%= model_class.human_attribute_name(:question_id) %>:</strong></dt>
  <dd><%= @variant.question_id %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              variants_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_variant_path(@variant), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              variant_path(@variant),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>